class systemd::weather {

# Creating file to run weather.sh command in background indefinitely like a service
file { '/usr/local/bin/weather-init.sh':
  mode    => '0755',
  owner   => 'root',
  group   => 'root',
  content => template('systemd/weather-init.erb'),
}

# This script on every minute creates a file with the current weather forecast for João Pessoa
file { '/usr/local/bin/weather.sh':
  mode    => '0755',
  owner   => 'root',
  group   => 'root',
  require => [
		Package["jq"], 
  		File["/usr/local/bin/weather-init.sh"],
	     ],
  content => template('systemd/weather-script.erb'),
}

# Creating a directory where storages the files created by weather.sh script
file {'weather-file':
   ensure => "directory",
   path   => '/root/weather-file',
   mode   => "0755",
   owner  => "root",
   group  => "root",
}

# This systemd service will run weather-init.sh command in background indefinitely like a service
file { '/lib/systemd/system/weather.service':
  mode    => '0644',
  owner   => 'root',
  group   => 'root',
  content => template('systemd/weather.service.erb'),
  require => File["/usr/local/bin/weather-init.sh", "/usr/local/bin/weather.sh"],
}~>
exec { 'weather-systemd-reload':
  command     => 'systemctl daemon-reload',
  path        => [ '/usr/bin', '/bin', '/usr/sbin' ],
  refreshonly => true,
}

service { 'weather':
  ensure   => running,
  enable   => true,
}

# This script backups files created by the service weather.service.
file { '/usr/local/bin/backup-weather.sh':
  mode    => '0755',
  owner   => 'root',
  group   => 'root',
  content => template('systemd/backup-weather.erb'),
}

# The cron will be executed once a day to create a backup from files generated by weather.service and
# will keep only the last 10 days backup.
cron {'Backuping Weatcher files':
   command => "/usr/local/bin/backup-weather.sh > /var/log/backup-weather.log  2>&1",
   user    => 'root',
   hour    =>  '23',
   minute  =>  '59',
   require => File["/usr/local/bin/backup-weather.sh"],
  }

# I installed this dependency using: puppet module install rehan-jq
include jq
}
